name: fermi-env
dependencies:
  - python=3.7.0
  - numpy=1.14.5
  - pip=10.0.1
  - python=3.6.2
  - python-dateutil=2.7.3
  - pytz=2018.5
  - scipy=1.1.0
  - setuptools=39.2.0
  - six=1.11.0
  - sqlite=3.24.0
  - pip:
    - awscli==1.14.56
    - blessed==1.14.2
    - botocore==1.9.9
    - cement==2.8.2
    - docker-py==1.7.2
    - dockerpty==0.4.1
    - docopt==0.6.2
    - docutils==0.14
    - jmespath==0.9.3
    - pyasn1==0.4.2
    - pymysql==0.8.0
    - requests==2.9.1
    - s3transfer==0.1.13
    - semantic-version==2.5.0
    - tabulate==0.7.5
